volumes:
  local_postgres_data: {}

services:
  postgres:
    image:
      postgres
    env_file:
      - .env
    ports:
      - '5300:5432'
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
