# Generated by Django 5.0.4 on 2024-04-11 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0004_alter_field_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='field_type',
            field=models.SmallIntegerField(choices=[('string', 'String'), ('number', 'Number'), ('boolean', 'boolean')]),
        ),
    ]
