# Generated by Django 5.0.4 on 2024-04-12 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0009_alter_table_options_remove_table_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='field',
            table=None,
        ),
    ]
