# Generated by Django 5.0.4 on 2024-04-10 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='field_type',
            field=models.SmallIntegerField(choices=[(0, 'string'), (1, 'number'), (2, 'boolen')]),
        ),
        migrations.AlterField(
            model_name='field',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='tables.table'),
        ),
    ]
