# Generated by Django 5.0.4 on 2024-04-10 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_alter_field_field_type_alter_field_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={'verbose_name': 'TableData'},
        ),
    ]
