# Generated by Django 5.0.4 on 2024-04-11 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_alter_table_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='field',
            table='table_fields',
        ),
    ]
