# Generated by Django 5.0.4 on 2024-04-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0006_alter_field_field_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='default_boolean',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='default_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='default_string',
            field=models.CharField(null=True),
        ),
    ]
