# Generated by Django 5.0.4 on 2024-04-11 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0007_field_default_boolean_field_default_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='field_type',
            field=models.CharField(choices=[('string', 'String'), ('number', 'Number'), ('boolean', 'Boolean')]),
        ),
    ]
